name = PV Log Browser
version = 1.0.0
date = March 25, 2004
authors = Tom Pelaia (SNS)
organization = Spallation Neutron Source
description = This application is used to browse the pvlogger archives.
