#!/bin/sh

CURRENT_DIR=`dirname $0`

cd $CURRENT_DIR/../../../openxal-score/packaging
mvn clean && mvn package
if [ $? -ne 0 ]; then
  echo Failed during packaging OpenXAL Score
	exit 1
fi

cd $CURRENT_DIR
