#!/bin/sh

CURRENT_DIR=`dirname $0`

cd $CURRENT_DIR/../../../openxal/core/packaging
mvn clean && mvn package
if [ $? -ne 0 ]; then
  echo Failed during packaging OpenXAL Core
	exit 1
fi

cd $CURRENT_DIR
