#!/bin/sh

CURRENT_DIR=`dirname $0`

cd $CURRENT_DIR/../../../openxal/apps/packaging
mvn clean && mvn package
if [ $? -ne 0 ]; then
  echo Failed during packaging OpenXAL Applications
	exit 1
fi

cd $CURRENT_DIR
