#!/bin/sh

CURRENT_DIR=`dirname $0`

cd $CURRENT_DIR/../../../jels/packaging/
mvn clean && mvn package
if [ $? -ne 0 ]; then
  echo Failed during packaging JELS or ESS Data
	exit 1
fi

cd $CURRENT_DIR
