#!/bin/sh

CURRENT_DIR=`dirname $0`

cd $CURRENT_DIR/../../../openxal/services/pvlogger/packaging
mvn clean && mvn package
if [ $? -ne 0 ]; then
  echo Failed during packaging OpenXAL PV Logger Service
	exit 1
fi

cd $CURRENT_DIR
