/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaterfallParamPanelNB.java
 *
 * Created on Mar 25, 2009, 1:47:22 PM
 */

package xal.app.lossviewer.dndcomponents.waterfall;

/**
 *
 * @author az9
 */
public class WaterfallParamPanelNB extends javax.swing.JPanel {
    private static final long serialVersionUID = -2909521003327574596L;

    /** Creates new form WaterfallParamPanelNB */
    public WaterfallParamPanelNB() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        minLabel = new javax.swing.JLabel();
        maxLabel = new javax.swing.JLabel();
        minTF = new javax.swing.JTextField();
        maxTF = new javax.swing.JTextField();
        logCB = new javax.swing.JCheckBox();
        blmNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        blmValueLabel = new javax.swing.JLabel();
        blmTimeLabel = new javax.swing.JLabel();
        blmColorValueLabel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        minLabel.setText("Min");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        add(minLabel, gridBagConstraints);

        maxLabel.setText("Max");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(maxLabel, gridBagConstraints);

        minTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        minTF.setMinimumSize(new java.awt.Dimension(50, 27));
        minTF.setPreferredSize(new java.awt.Dimension(50, 20));
        minTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(minTF, gridBagConstraints);

        maxTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        maxTF.setMinimumSize(new java.awt.Dimension(50, 27));
        maxTF.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(maxTF, gridBagConstraints);

        logCB.setText("log scale");
        logCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(logCB, gridBagConstraints);

        blmNameLabel.setText("BLM Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(blmNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        add(jLabel1, gridBagConstraints);

        blmValueLabel.setText("Value");
        blmValueLabel.setPreferredSize(new java.awt.Dimension(70, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(blmValueLabel, gridBagConstraints);

        blmTimeLabel.setText("Timestamp");
        blmTimeLabel.setPreferredSize(new java.awt.Dimension(70, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(blmTimeLabel, gridBagConstraints);

        blmColorValueLabel.setBackground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(blmColorValueLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weightx = 1.0;
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void minTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_minTFActionPerformed

    private void logCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logCBActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_logCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel blmColorValueLabel;
    protected javax.swing.JLabel blmNameLabel;
    protected javax.swing.JLabel blmTimeLabel;
    protected javax.swing.JLabel blmValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JCheckBox logCB;
    private javax.swing.JLabel maxLabel;
    protected javax.swing.JTextField maxTF;
    private javax.swing.JLabel minLabel;
    protected javax.swing.JTextField minTF;
    // End of variables declaration//GEN-END:variables

}
