#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: package-openxal COMMAND"
    echo "   COMMAND = package,install,deploy - appropriate Maven directive"
    
    echo " Command assumes following projects are side-by-side in the directory structure: "
    echo "  openxal-deps "
    echo "  openxal"
    
    exit 1
fi

COMMAND=$1
CURRENT_DIR_TEMP=`dirname $0`
CURRENT_DIR=`readlink -f $CURRENT_DIR_TEMP`


# Build openxal 
cd $CURRENT_DIR/../../openxal
mvn -s ~/.m2/settings.xml clean && mvn -s ~/.m2/settings.xml $COMMAND
if [ $? -ne 0 ]; then
    echo Failed on building openxal
    exit 2
fi

