#!/bin/bash
#-------------------------------------------------------------------------------
# Script that builds OpenXAL distribution RPMs
#
#
#
# Author: miroslav.pavleski@cosylab.com
#-------------------------------------------------------------------------------

GREEN='\e[0;32m'
YELLOW='\e[1;33m'
RED='\e[0;31m'
NC='\e[0m'

if [ -z "$1" ]; then
    echo "Usage: package-openxal DESTINATION_PATH_FOR_RPMs"
    echo ""
    echo " Command assumes following projects are side-by-side in the directory structure: "
    echo ""
    echo "  openxal"
    echo "  openxal-score"
    
    exit 1
fi

DESTINATION_DIR="$1"
if [ -z "$PROJECTDIR" ]; then
    # Assuming we are in openxal/packaging 
    PROJECTDIR=`readlink -f  $(pwd)/..`
    echo PROJECTDIR not defined. Defaulting to $PROJECTDIR
fi

#-------------------------------------------------------------------------------
# List all directories containing RPM building pom.xml-s
#
# Here we list RPM pom.xml directories
# !! Note: Order importand, the packages bellow might depend on the packages at the top.
#
#-------------------------------------------------------------------------------
declare -a RPM_DIRS=(
    # ESS configuration specific data
    "$PROJECTDIR/packaging/ess-data"
    
    # Core libraries
    "$PROJECTDIR/core/packaging"

    # OpenXAL applications
    "$PROJECTDIR/apps/packaging/bricks"
    "$PROJECTDIR/apps/packaging/dbbrowser"
    "$PROJECTDIR/apps/packaging/extlatgenerator"
    "$PROJECTDIR/apps/packaging/knobs"
    "$PROJECTDIR/apps/packaging/launcher"
    "$PROJECTDIR/apps/packaging/machinesimulator"
    "$PROJECTDIR/apps/packaging/mtv"
    "$PROJECTDIR/apps/packaging/opticseditor"
    "$PROJECTDIR/apps/packaging/opticsswitcher"
    "$PROJECTDIR/apps/packaging/orbitcorrect"
    "$PROJECTDIR/apps/packaging/pvhistogram"
    "$PROJECTDIR/apps/packaging/pvlogger"
    "$PROJECTDIR/apps/packaging/scan1d"
    "$PROJECTDIR/apps/packaging/scan2d"
    "$PROJECTDIR/apps/packaging/scope"
    "$PROJECTDIR/apps/packaging/score"
    "$PROJECTDIR/apps/packaging/virtualaccelerator"
    "$PROJECTDIR/apps/packaging/xyzcorrelator"
    
    # PV Logger Service
    "$PROJECTDIR/services/pvlogger/packaging"
        
    # The OpenXAL meta-package
    "$PROJECTDIR/packaging/openxal-meta"
)

#-------------------------------------------------------------------------------
# Clean, build and RPM Upgrade all RPMs in order
#-------------------------------------------------------------------------------
for i in "${RPM_DIRS[@]}"
do
    printf "\n\n${YELLOW}Building RPM in $i directory.${NC}\n\n"
    
    cd "$i"
    if [ $? -ne 0 ]; then
        echo ${RED}Invalid RPM project directory detected: $i ${NC}
        exit 2
    fi
    
    mvn clean && mvn package
    if [ $? -ne 0 ]; then
        echo ${RED}Failed to package project in $i ${NC}
        exit 3
    fi

    sudo rpm -U --replacepkgs --replacefiles target/*.rpm
    if [ $? -ne 0 ]; then
        echo ${RED}RPM Install failed for $i ${NC}
        exit 4
    fi
done
cd "$PROJECTDIR"


#-------------------------------------------------------------------------------
# Copy RPMs to destination directory
#-------------------------------------------------------------------------------
printf "\n\n${GREEN}RPM Packages built successfully.\nCopying to $DESTINATION_DIR  ..."
for i in "${RPM_DIRS[@]}"
do
    cp -f "$i"/target/*.rpm "$DESTINATION_DIR"
done
printf "DONE.${NC}\n\n"
